### ISSUE TITLE
coding: Adjust the Navbar

### ISSUE THREAD

**Issue by khushishikhu** [Feminine-Divine/periodo#112]
**Describe the bug**
Adjust the Navbar. Currently user is not able to see all the tabs available on the navbar. Also decrease the height of navbar to size which is considered as fit for it.

**To Reproduce**
1. Go to 'Navbar'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/65439761/111868678-598bb480-89a1-11eb-88c7-6d6757afbddf.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser [chrome]

**Comment by mdPial** [comment]
I would like to work on that issue.

**Comment by nehathakur27** [comment]
I would like to work on it.

**Comment by khushishikhu** [comment]
@mdPial assigning this to you. Happy Coding!! 
@nehathakur27 you can look for any other issue on which the work isn't started yet don't and the assigned one haven't given any updates on it😊

**Comment by mdPial** [comment]
@khushishikhu  I have found some code issues in the `navbar.js` file.

- semicolons are not given in some line
- more than one break lines between some lines
- code is not formatted
- instead of **className** used **class**
- instead of **htmlFor** used **for**
- `img` tag has a separate opening and closing tag
- `Typography` component imported + used but don't have any text inside that

Should I change those?

**Comment by khushishikhu** [comment]
@mdPial you are already assigned to an issue I guess so let others also give chance to contribute. @nehathakur27 assigning this to you

**Comment by khushishikhu** [comment]
@mdPial yes you can change those👍
