### ISSUE TITLE
Add contributors list in website, Feature request!

### ISSUE THREAD

**Issue by akshay1027** [Feminine-Divine/periodo#232]
## Is your feature request related to a problem? Please describe.
 Since this is an open-source project, it would be great the add a contributors list to our website. Would love to do this. we can do this in the home page or about us page IMO. Thank you and let me know @khushishikhu @Aaishpra.

**Comment by Aaishpra** [comment]
Sorry @akshay1027 I am not in favour for implementing this feature as this will make the website look bulky. 
Although i do understand your point, but it's just not in my preference to add something related to the project developers in the website, that's why u will never see even my name and Khushi's name in the readme and website.

**Comment by akshay1027** [comment]
Cool!
